'use client';

import { useState } from 'react';
import { AlertTriangle, Plus, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { AREA_CLASS, CreateAlertMode, Match, Receiver, Rule, Severity } from '@/components/alerts/types';
import { Field } from '@/components/alerts/AlertEditors';

interface CreateAlertModalProps {
  mode: CreateAlertMode;
  onModeChange: (mode: CreateAlertMode) => void;
  rule: Rule;
  onRuleChange: (rule: Rule) => void;
  sourceYaml: string;
  onSourceYamlChange: (yaml: string) => void;
  error: string;
  saving: boolean;
  onClose: () => void;
  onAddRule: () => void;
  onImportYaml: () => void;
}

export function CreateAlertModal({ mode, onModeChange, rule, onRuleChange, sourceYaml, onSourceYamlChange, error, saving, onClose, onAddRule, onImportYaml }: CreateAlertModalProps) {
  const setRule = (patch: Partial<Rule>) => onRuleChange({ ...rule, ...patch });
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4" role="dialog" aria-modal="true" aria-labelledby="create-alert-title" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}>
    <div className="w-full max-w-3xl max-h-[calc(100vh-2rem)] overflow-y-auto rounded-lg border border-border bg-card shadow-2xl">
      <div className="flex items-start justify-between border-b border-border px-5 py-4"><div><h2 id="create-alert-title" className="text-base font-semibold">New alert</h2><p className="mt-0.5 text-xs text-muted-foreground">Choose a configuration method, complete the fields here, and add it to the current configuration</p></div><Button variant="ghost" size="icon" title="Close" onClick={onClose}>×</Button></div>
      <div className="grid grid-cols-2 gap-2 border-b border-border p-4"><button type="button" className={`rounded-md border px-3 py-2 text-left text-sm ${mode === 'rule' ? 'border-primary bg-primary/10' : 'border-border hover:bg-muted'}`} onClick={() => onModeChange('rule')}><span className="block font-medium">Create rule from form</span><span className="mt-0.5 block text-xs text-muted-foreground">Enter PromQL and alert metadata</span></button><button type="button" className={`rounded-md border px-3 py-2 text-left text-sm ${mode === 'prometheus-rules' ? 'border-primary bg-primary/10' : 'border-border hover:bg-muted'}`} onClick={() => onModeChange('prometheus-rules')}><span className="block font-medium">Parse Prometheus rule YAML</span><span className="mt-0.5 block text-xs text-muted-foreground">Import groups and rules</span></button></div>
      <div className="p-5">
        {mode === 'rule' ? <div className="grid gap-3 md:grid-cols-2"><Field label="Rule name"><input className="w-full h-8 rounded-md border border-input bg-background px-2.5 text-sm outline-none focus:ring-2 focus:ring-ring/40" value={rule.ruleName} onChange={(e) => setRule({ ruleName: e.target.value })} /></Field><Field label="Group"><input className="w-full h-8 rounded-md border border-input bg-background px-2.5 text-sm outline-none focus:ring-2 focus:ring-ring/40" value={rule.groupName} onChange={(e) => setRule({ groupName: e.target.value })} /></Field><Field label="Evaluation interval (seconds)"><input className="w-full h-8 rounded-md border border-input bg-background px-2.5 text-sm outline-none focus:ring-2 focus:ring-ring/40" type="number" min="1" value={rule.intervalSec} onChange={(e) => setRule({ intervalSec: Number(e.target.value) })} /></Field><Field label="Duration"><input className="w-full h-8 rounded-md border border-input bg-background px-2.5 text-sm outline-none focus:ring-2 focus:ring-ring/40" placeholder="e.g. 2m" value={rule.forDuration} onChange={(e) => setRule({ forDuration: e.target.value })} /></Field><Field label="Severity"><select className="w-full h-8 rounded-md border border-input bg-background px-2.5 text-sm outline-none focus:ring-2 focus:ring-ring/40" value={rule.severity} onChange={(e) => setRule({ severity: e.target.value as Severity })}><option value="critical">critical</option><option value="warning">warning</option><option value="info">info</option></select></Field><Field label="Summary"><input className="w-full h-8 rounded-md border border-input bg-background px-2.5 text-sm outline-none focus:ring-2 focus:ring-ring/40" value={rule.summary} onChange={(e) => setRule({ summary: e.target.value })} /></Field><Field label="PromQL expression" wide><textarea className="w-full min-h-20 rounded-md border border-input bg-background px-2.5 py-1.5 text-sm font-mono outline-none focus:ring-2 focus:ring-ring/40" value={rule.expression} onChange={(e) => setRule({ expression: e.target.value })} /></Field><Field label="Description" wide><textarea className="w-full min-h-20 rounded-md border border-input bg-background px-2.5 py-1.5 text-sm font-mono outline-none focus:ring-2 focus:ring-ring/40" value={rule.description} onChange={(e) => setRule({ description: e.target.value })} /></Field></div> : <div className="space-y-3"><p className="text-xs text-muted-foreground">Paste Prometheus alert rule YAML containing <code>groups</code> and <code>rules</code>; parsed rules will be appended to the current alert rules.</p><textarea className={`${AREA_CLASS} min-h-64`} value={sourceYaml} onChange={(e) => onSourceYamlChange(e.target.value)} placeholder={'groups:\n  - name: castrel-custom\n    interval: 30s\n    rules:\n      - alert: ServiceDown\n        expr: up == 0\n        for: 1m\n        labels:\n          severity: critical\n        annotations:\n          summary: Service unavailable'} /></div>}
      </div>
      {error && <div className="mx-5 mb-3 flex gap-2 items-start rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive"><AlertTriangle className="size-4 mt-0.5 shrink-0" />{error}</div>}<div className="flex justify-end gap-2 border-t border-border px-5 py-3"><Button variant="outline" onClick={onClose}>Cancel</Button>{mode === 'rule' ? <Button onClick={onAddRule} disabled={saving || !rule.ruleName.trim() || !rule.expression.trim()}><Plus />Add rule</Button> : <Button onClick={onImportYaml} disabled={saving || !sourceYaml.trim()}><RefreshCw />{saving ? 'Parsing...' : 'Parse and apply'}</Button>}</div>
    </div>
  </div>;
}

interface ReceiverModalProps {
  receiver: Receiver;
  onChange: (receiver: Receiver) => void;
  sourceYaml: string;
  onSourceYamlChange: (yaml: string) => void;
  error: string;
  saving: boolean;
  onClose: () => void;
  onAdd: () => void;
  onImportYaml: () => void;
}

export function ReceiverModal({ receiver, onChange, sourceYaml, onSourceYamlChange, error, saving, onClose, onAdd, onImportYaml }: ReceiverModalProps) {
  const [mode, setMode] = useState<'form' | 'yaml'>('form');
  const set = (patch: Partial<Receiver>) => onChange({ ...receiver, ...patch });
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4" role="dialog" aria-modal="true" aria-labelledby="create-receiver-title" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}>
    <div className="w-full max-w-2xl rounded-lg border border-border bg-card shadow-2xl">
      <div className="flex items-start justify-between border-b border-border px-5 py-4"><div><h2 id="create-receiver-title" className="text-base font-semibold">New receiver</h2><p className="mt-0.5 text-xs text-muted-foreground">Configure Webhook and optional Basic Auth</p></div><Button variant="ghost" size="icon" title="Close" onClick={onClose}>×</Button></div>
      <div className="grid grid-cols-2 gap-2 border-b border-border p-4"><button type="button" className={`rounded-md border px-3 py-2 text-left text-sm ${mode === 'form' ? 'border-primary bg-primary/10' : 'border-border hover:bg-muted'}`} onClick={() => setMode('form')}><span className="block font-medium">Configure receiver from form</span><span className="mt-0.5 block text-xs text-muted-foreground">Enter Webhook and authentication details</span></button><button type="button" className={`rounded-md border px-3 py-2 text-left text-sm ${mode === 'yaml' ? 'border-primary bg-primary/10' : 'border-border hover:bg-muted'}`} onClick={() => setMode('yaml')}><span className="block font-medium">Parse Alertmanager YAML</span><span className="mt-0.5 block text-xs text-muted-foreground">Import route and receivers directly</span></button></div>
      {mode === 'form' ? <div className="grid gap-3 p-5 md:grid-cols-2"><Field label="Receiver name"><input className="w-full h-8 rounded-md border border-input bg-background px-2.5 text-sm outline-none focus:ring-2 focus:ring-ring/40" value={receiver.receiverName} onChange={(e) => set({ receiverName: e.target.value })} /></Field><Field label="Severity match"><select className="w-full h-8 rounded-md border border-input bg-background px-2.5 text-sm outline-none focus:ring-2 focus:ring-ring/40" value={receiver.severityMatch} onChange={(e) => set({ severityMatch: e.target.value as Match })}><option value="all">All</option><option value="critical">critical</option><option value="warning">warning</option><option value="info">info</option></select></Field><Field label="Webhook URL" wide><input className="w-full h-8 rounded-md border border-input bg-background px-2.5 text-sm outline-none focus:ring-2 focus:ring-ring/40" type="url" value={receiver.endpoint} onChange={(e) => set({ endpoint: e.target.value })} /></Field><Field label="Basic Auth username"><input className="w-full h-8 rounded-md border border-input bg-background px-2.5 text-sm outline-none focus:ring-2 focus:ring-ring/40" value={receiver.basicAuthUsername ?? ''} onChange={(e) => set({ basicAuthUsername: e.target.value })} /></Field><Field label="Basic Auth password"><input className="w-full h-8 rounded-md border border-input bg-background px-2.5 text-sm outline-none focus:ring-2 focus:ring-ring/40" type="password" value={receiver.basicAuthPassword ?? ''} onChange={(e) => set({ basicAuthPassword: e.target.value })} /></Field><div className="flex items-center gap-4 md:col-span-2"><label className="text-xs flex items-center gap-1.5"><input type="checkbox" checked={receiver.sendResolved} onChange={(e) => set({ sendResolved: e.target.checked })} />Send resolved notifications</label><label className="text-xs flex items-center gap-1.5"><input type="checkbox" checked={receiver.enabled} onChange={(e) => set({ enabled: e.target.checked })} />Enabled</label></div></div> : <div className="space-y-3 p-5"><p className="text-xs text-muted-foreground">Paste Alertmanager YAML containing <code>route</code> and <code>receivers</code>; parsed content will update receivers and routes.</p><textarea className={`${AREA_CLASS} min-h-64`} value={sourceYaml} onChange={(e) => onSourceYamlChange(e.target.value)} placeholder={'route:\n  receiver: "keep"\nreceivers:\n  - name: "keep"\n    webhook_configs:\n      - url: "https://example.com/alerts"'} /></div>}
      {error && <div className="mx-5 mb-3 flex gap-2 items-start rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive"><AlertTriangle className="size-4 mt-0.5 shrink-0" />{error}</div>}<div className="flex justify-end gap-2 border-t border-border px-5 py-3"><Button variant="outline" onClick={onClose}>Cancel</Button>{mode === 'form' ? <Button onClick={onAdd} disabled={saving || !receiver.receiverName.trim() || !/^https?:\/\//.test(receiver.endpoint)}><Plus />Add receiver</Button> : <Button onClick={onImportYaml} disabled={saving || !sourceYaml.trim()}><RefreshCw />{saving ? 'Parsing...' : 'Parse and apply'}</Button>}</div>
    </div>
  </div>;
}

export function RouteModal({ route, onChange, saving, onClose, onAdd }: { route: import('@/components/alerts/types').AlertRoute; onChange: (route: import('@/components/alerts/types').AlertRoute) => void; saving: boolean; onClose: () => void; onAdd: () => void }) {
  const set = (patch: Partial<typeof route>) => onChange({ ...route, ...patch });
  const matchText = Object.entries(route.match).map(([key, value]) => `${key}=${value}`).join(', ');
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4" role="dialog" aria-modal="true" aria-labelledby="create-route-title" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}>
    <div className="w-full max-w-2xl rounded-lg border border-border bg-card shadow-2xl">
      <div className="flex items-start justify-between border-b border-border px-5 py-4"><div><h2 id="create-route-title" className="text-base font-semibold">New route</h2><p className="mt-0.5 text-xs text-muted-foreground">Match alerts by labels and send them to the specified receiver</p></div><Button variant="ghost" size="icon" title="Close" onClick={onClose}>×</Button></div>
      <div className="grid gap-3 p-5 md:grid-cols-2"><Field label="receiver"><input className="w-full h-8 rounded-md border border-input bg-background px-2.5 text-sm outline-none focus:ring-2 focus:ring-ring/40" value={route.receiver} onChange={(e) => set({ receiver: e.target.value })} /></Field><Field label="Matching labels" wide><input className="w-full h-8 rounded-md border border-input bg-background px-2.5 text-sm outline-none focus:ring-2 focus:ring-ring/40" value={matchText} placeholder="e.g. severity=critical, service=order" onChange={(e) => set({ match: Object.fromEntries(e.target.value.split(',').map((item) => item.trim().split('=').map((part) => part.trim())).filter(([key, value]) => key && value)) })} /></Field><Field label="group_by（optional）"><input className="w-full h-8 rounded-md border border-input bg-background px-2.5 text-sm outline-none focus:ring-2 focus:ring-ring/40" value={route.groupBy?.join(', ') ?? ''} onChange={(e) => set({ groupBy: e.target.value.split(',').map((item) => item.trim()).filter(Boolean) || undefined })} /></Field><Field label="group_wait（optional）"><input className="w-full h-8 rounded-md border border-input bg-background px-2.5 text-sm outline-none focus:ring-2 focus:ring-ring/40" value={route.groupWait ?? ''} onChange={(e) => set({ groupWait: e.target.value || undefined })} /></Field><Field label="group_interval（optional）"><input className="w-full h-8 rounded-md border border-input bg-background px-2.5 text-sm outline-none focus:ring-2 focus:ring-ring/40" value={route.groupInterval ?? ''} onChange={(e) => set({ groupInterval: e.target.value || undefined })} /></Field><Field label="repeat_interval（optional）"><input className="w-full h-8 rounded-md border border-input bg-background px-2.5 text-sm outline-none focus:ring-2 focus:ring-ring/40" value={route.repeatInterval ?? ''} onChange={(e) => set({ repeatInterval: e.target.value || undefined })} /></Field><label className="text-xs flex items-center gap-1.5 md:col-span-2"><input type="checkbox" checked={route.continue} onChange={(e) => set({ continue: e.target.checked })} />Continue processing subsequent routes after a match</label></div>
      <div className="flex justify-end gap-2 border-t border-border px-5 py-3"><Button variant="outline" onClick={onClose}>Cancel</Button><Button onClick={onAdd} disabled={saving || !route.receiver.trim() || !Object.keys(route.match).length}><Plus />Add route</Button></div>
    </div>
  </div>;
}
