apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: castrel-shopfront
  namespace: castrel
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: shopfront.castrel.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shopfront
                port:
                  number: 3090
