server:
  port: 8085

spring:
  application:
    name: payment-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:13306/castrel?useSSL=false&serverTimezone=Asia/Shanghai&connectionTimeZone=%2B08:00&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:castrel}
    password: ${SPRING_DATASOURCE_PASSWORD:castrel}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:16379}

payment:
  psp-timeout-ms: 2000

services:
  order-url: ${ORDER_SERVICE_URL:http://localhost:8084}
  psp-url: ${PSP_SIMULATOR_URL:http://localhost:8092}

management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,schemaVersion
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  prometheus:
    metrics:
      export:
        enabled: true
