server:
  port: 8084

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/castrel?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: castrel
    password: castrel
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379

services:
  user-url: http://localhost:8081
  catalog-url: http://localhost:8082
  inventory-url: http://localhost:8083
  payment-url: http://localhost:8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  prometheus:
    metrics:
      export:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/castrel?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  data:
    redis:
      host: redis

services:
  user-url: http://user-service:8081
  catalog-url: http://catalog-service:8082
  inventory-url: http://toxiproxy:18083
  payment-url: http://toxiproxy:18085
