package com.castrel.chaos.order.dto;

import lombok.Data;

@Data
public class CreateOrderRequest {
    private String orderNo;  // idempotency key; generated by caller or runner
    private Long userId;
    private String sku;
    private Integer qty;
}
