global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:8080']
        labels:
          service: 'gateway'

  - job_name: 'user'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8081']
        labels:
          service: 'user'

  - job_name: 'catalog'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['catalog-service:8082']
        labels:
          service: 'catalog'

  - job_name: 'inventory'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['inventory-service:8083']
        labels:
          service: 'inventory'

  - job_name: 'order'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8084']
        labels:
          service: 'order'

  - job_name: 'payment'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8085']
        labels:
          service: 'payment'

  - job_name: 'traffic-control-plane'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['traffic-control-plane:3086']
        labels:
          service: 'traffic-control-plane'

  - job_name: 'promotion'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['promotion-service:8087']
        labels:
          service: 'promotion'

  - job_name: 'risk'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['risk-service:8088']
        labels:
          service: 'risk'

  - job_name: 'fulfillment'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['fulfillment-service:8089']
        labels:
          service: 'fulfillment'

  - job_name: 'notification'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8090']
        labels:
          service: 'notification'

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']
        labels:
          service: 'mysql'

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node'
