apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: castrel
data:
  SPRING_PROFILES_ACTIVE: "docker,chaos"
  CASTREL_JWT_ISSUER: "castrel-user-service"
  CASTREL_JWT_AUDIENCE: "castrel-gateway"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/castrel?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus"
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
  OBSERVABILITY_ENABLED: "true"
  OBSERVABILITY_OTLP_TRANSPORT: "http"
  OBSERVABILITY_OTLP_ENDPOINT: "http://tempo:4318/v1/traces"
  CART_SERVICE_URL: "http://cart-service:8091"
  USER_SERVICE_URL: "http://user-service:8081"
  ORDER_SERVICE_URL: "http://order-service:8084"
  CATALOG_SERVICE_URL: "http://catalog-service:8082"
  INVENTORY_SERVICE_URL: "http://inventory-service:8083"
  PAYMENT_SERVICE_URL: "http://payment-service:8085"
  PROMOTION_SERVICE_URL: "http://promotion-service:8087"
  RISK_SERVICE_URL: "http://risk-service:8088"
  FULFILLMENT_SERVICE_URL: "http://fulfillment-service:8089"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8090"
  CHAOS_ORDER_URL: "http://order-service:8084"
  CHAOS_PAYMENT_URL: "http://payment-service:8085"
  CHAOS_CATALOG_URL: "http://catalog-service:8082"
  CHAOS_INVENTORY_URL: "http://inventory-service:8083"
  CHAOS_PROMOTION_URL: "http://promotion-service:8087"
  CHAOS_RISK_URL: "http://risk-service:8088"
  CHAOS_FULFILLMENT_URL: "http://fulfillment-service:8089"
  CHAOS_NOTIFICATION_URL: "http://notification-service:8090"
  TOXIPROXY_API_URL: "http://toxiproxy:8474"
  CHAOS_CONSOLE_GRAFANA_BASE_URL: ""
  TRAFFIC_LIFECYCLE_LOGIN_ENABLED: "false"
  JAVA_OPTS: "-Xms256m -Xmx512m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heapdump.hprof"
